### ISSUE TITLE
Miner: Partidos políticos

### ISSUE THREAD

**Issue by alganet** [Aeronautics/Spitfire#2]
Criar um miner (vide `vereadores.php`) chamado `partidos.php` que consuma o HTML de [Lista de Partidos do TSE](http://www.tse.jus.br/partidos/partidos-politicos) e os detalhes de cada partido em HTML também, que podem ser encontrados através do link acima.
É possível e ideal que o miner navegue entre nos links dos partidos para buscar as informações de cada partido automaticamente.

Provavelmente algum componentede seleção de elementos usando CSS seja desejado, o Respect/Template usa um bom componente do Zend Framework para isso.

**Comment by wesleyvicthor** [comment]
Senhores(as), rodar vereadores.php em seguida partidos.php

**Comment by alganet** [comment]
Aqui deu isso:

PHP Warning:  array_combine(): Both parameters should have an equal number of elements in /home/alganet/Projects/Aeronautics/Spitfire/miner/partidos.php on line 31
PHP Stack trace:
PHP   1. {main}() /home/alganet/Projects/Aeronautics/Spitfire/miner/partidos.php:0
PHP   2. {closure}() /home/alganet/Projects/Aeronautics/Spitfire/miner/partidos.php:104
PHP   3. {closure}() /home/alganet/Projects/Aeronautics/Spitfire/miner/partidos.php:45
PHP   4. array_combine() /home/alganet/Projects/Aeronautics/Spitfire/miner/partidos.php:31

> > PMDB parsing data from http://www.tse.jus.br/partidos/partidos-politicos/partido-do-movimento-democratico-brasileiro
> > SQLSTATE[42S22]: Column not found: 1054 Unknown column 'presidenteNacional' in 'field list'
> > #0 /usr/share/php/Respect/Relational/Db.php(86): PDOStatement->execute(Array)
> > #1 /usr/share/php/Respect/Relational/Db.php(30): Respect\Relational\Db->executeStatement()
> > #2 /usr/share/php/Respect/Relational/Mapper.php(152): Respect\Relational\Db->exec()
> > #3 /usr/share/php/Respect/Relational/Mapper.php(100): Respect\Relational\Mapper->rawInsert(Array, 'partido', Object(stdClass))
> > #4 /usr/share/php/Respect/Relational/Mapper.php(81): Respect\Relational\Mapper->flushSingle(Object(stdClass))
> > #5 /home/alganet/Projects/Aeronautics/Spitfire/miner/partidos.php(97): Respect\Relational\Mapper->flush()
> > #6 /home/alganet/Projects/Aeronautics/Spitfire/miner/partidos.php(104): {closure}()
> > #7 {main}

**Comment by wesleyvicthor** [comment]
você atualizou a tabela ?

<del>o warning é preguiça mesmo.</del>


pull novamente e atualiza a tabela vei!
